version: '3.8'
services:

  myapp:
    build: baiduapp
    image: baiduapp:1.0
    container_name: baiduapp

    volumes:

      - ./data/logs:/tmp/nas-file/logs

      - ./data/data:/data

      - ./data/volume1:/sdkpath/volume1

    networks:
      - baiduapp

    environment:
      - API_HOST=127.0.0.1:8091

    ports:
      - "8092:8080/tcp"

    restart: always

networks:
  baiduapp:
    driver: bridge
